import type { Metadata } from 'next'
import { Source_Code_Pro, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";

const source_code_pro = Source_Code_Pro({
  weight: ["400", "600"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

const ibm = IBM_Plex_Sans({
  weight: "400",
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ibm.className}>{children}</body>
    </html>
  );
}
